@startuml SA6_uml

package SA6 {

    package ns_tb {
        class ToolBox {
            + std::string CSVReader(string file, int id)
            + bool CSVWriterParkLogs(string file, string idVoiture)
            + string floatTabToString(vector<float> tab, char delimiter)
            + vector<string> StringToTab(string tab, char delimiter)
            + bool LogSorter(string file)
            + int getNbLines(string file)
        }
    }
    
    class Parking {
        - float s_prix;
        - string filePath;
        - string s_infoVoiture;
        - string s_parkingData[5];
        - vector<string> idVoiture;

        + Parking(int id, float defaultPrice, int capacite_max, string cheminFichier)
        + Parking(int id, string cheminFichier)
        + ~Parking()
        + int getPort()
        + bool demarerServer()
        + string protocoleCommunication(string message, int etape)
        - bool EstRempli();
        - int readLog(int id);
        - string ajouterVoiture();
        - float calcul_prix(vector<string> tab);
    }

    Class Voiture {
        - int v_etape;
        - int v_id;
        - int v_prixBase;
        - float prixVoulu;
        - string v_path;
        - string v_voitureData[6];
        - vector<float> v_tab;
        
        + Voiture(int id, string name, string marque, string statut, string handicap, string age, string heure)
        + Voiture(int id, string filePath)
        + ~Voiture()
        + int getID()
        + bool connexionServer(int port)
        - float calcul_prix()
        - vector<float> initTab()
        - string protocoleCommunication(string message)
        - bool communicateWithParking(SocketVoiture client, string replyServer)
    }

    package Réseau <<Rectangle>> {

        package ns_server {
            Class ServerParking {
                + bool Receive(SOCKET socket, string& _buffer)
                + bool Server(int port, Parking * parking)
            }
        }

        Class SocketVoiture {
            - SOCKET mSocket

            + SocketVoiture();
            + ~SocketVoiture();
            + bool Connect(const std::string& ipaddress, unsigned short port);
            + int Send(const char* data, unsigned int len);
            + int Receive(char* buffer, unsigned int len);		
        }

        package ns_sockets{

            Class Sockets {

                + bool Start();
                + void Release();
                + int GetError();
                + void CloseSocket(SOCKET socket);
                + bool SetNonBlocking(SOCKET s)
                + string ConvertAddr(const sockaddr_in& addr)    
            }
        }
    }
}

ToolBox --o Voiture
ToolBox --o Parking

Parking "1 " *-- "1  " ServerParking : > possède
Voiture "1  " *-- "1 " SocketVoiture : possède >

SocketVoiture o-- Sockets
ServerParking o-- Sockets


@enduml